services:
  postgres:
    image: postgres:16
    container_name: pomodoro-postgres
    restart: unless-stopped
    env_file:
      - ./env/.env.dev
    volumes:
      - postgres-data:/var/lib/postgresql/data
      - ./db/init.sql:/docker-entrypoint-initdb.d/init.sql:ro
    ports:
      - "5432:5432"
    networks:
      - pomodoro-net

  redis:
    image: redis:7
    container_name: pomodoro-redis
    restart: unless-stopped
    ports:
      - "6379:6379"
    networks:
      - pomodoro-net

networks:
  pomodoro-net:

volumes:
  postgres-data:
